volumes:
  demo_temporal_pg_data:
networks:
  demo:
services:
  pg:
    image: postgres:16.8-alpine
    volumes:
      - demo_temporal_pg_data:/var/lib/postgresql/data
    networks:
      - demo
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      PGPORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: demo-temporal-pg
    restart: always
  temporal:
    depends_on:
      - pg
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    networks:
      - demo
    ports:
      - ${TEMPORAL_PORT}:7233
    environment:
      - DB=postgres12
      - DB_PORT=${POSTGRES_PORT}
      - POSTGRES_SEEDS=pg
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - TEMPORAL_ADDRESS=temporal:${TEMPORAL_PORT}
    container_name: demo-temporal
    restart: always
  temporal-admin-tools:
    depends_on:
      - temporal
    image: temporalio/admin-tools:${TEMPORAL_VERSION}
    networks:
      - demo
    environment:
      - TEMPORAL_ADDRESS=temporal:${TEMPORAL_PORT}
      - TEMPORAL_CLI_ADDRESS=temporal:${TEMPORAL_PORT}
    container_name: demo-temporal-admin-tools
    restart: always
    stdin_open: true
    tty: true
  temporal-ui:
    depends_on:
      - temporal
    image: temporalio/ui:2.37.2
    networks:
      - demo
    ports:
      - 8080:8080
    environment:
      - TEMPORAL_ADDRESS=temporal:${TEMPORAL_PORT}
    container_name: demo-temporal-ui
    restart: always
